apiVersion: v2
name: replicasense
description: Self-hosted, KEDA-native predictive autoscaling extension
type: application
version: 0.3.1
appVersion: "0.3.1"
kubeVersion: ">=1.28.0-0"
keywords:
  - keda
  - autoscaling
  - predictive
  - kubernetes
home: https://github.com/canberkturan/keda-replica-sense
sources:
  - https://github.com/canberkturan/keda-replica-sense
maintainers:
  - name: Canberk TURAN
annotations:
  artifacthub.io/category: ai-machine-learning
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/canberkturan/keda-replica-sense
    - name: Documentation
      url: https://github.com/canberkturan/keda-replica-sense/tree/main/docs
    - name: Support
      url: https://github.com/canberkturan/keda-replica-sense/issues
  artifacthub.io/images: |
    - name: Controller
      image: ghcr.io/canberkturan/replicasense-controller:0.3.1
    - name: Sampler
      image: ghcr.io/canberkturan/replicasense-sampler:0.3.1
    - name: External scaler
      image: ghcr.io/canberkturan/replicasense-scaler:0.3.1
    - name: XGBoost forecaster
      image: ghcr.io/canberkturan/replicasense-forecaster:0.3.1-xgboost
    - name: XGBoost trainer
      image: ghcr.io/canberkturan/replicasense-trainer:0.3.1-xgboost
    - name: Training scheduler
      image: ghcr.io/canberkturan/replicasense-training-scheduler:0.3.1
